version: '3.8'

services:
  postgres:
    build: ./db
    container_name: webpraia_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webpraia_database
      POSTGRES_USER: webpraiaadmin
      POSTGRES_PASSWORD: webpraiaadmin
    volumes:
      - ./db/volumes/webpraia:/var/lib/postgresql/data
    user: "${UID}:${GID}"